Repository Moka-react/SharingStudy, pull requests merged in 2020-06, with the labels that each got.

#16 Create [2주차] Context,Redux 기초.md
  LEEYOUNGJUN/[2주차] Context,Redux 기초.md
Labels: React

#15 2주차 라이프사이클 react 공부
  chelynn/리액트라이프사이클.md
Labels: React

#14 2주차 : 메서드와 this
  README.md
  doowan/2주차.md
  doowan/GarbageCollection.md
  doowan/Object.md
Labels: JavaScript

#13 2nd week done
  jgam/2week.md
Labels: TypeScript

#12 2주차 React life cycle
  danielPark/2week.md
Labels: React

#11 2주차 디자인 패턴 중 모듈패턴에 대한 공부내용
  jayden/1주차 프로토타입.md
  jayden/2주차 모듈패턴.md
Labels: JavaScript

#10 2주차 : 타입 스크립트
  MK/SSR/src/About.js
  MK/SSR/src/Home.js
  MK/Type/2week.md
Labels: TypeScript
